name: 24/7 Live Stream
on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'Direct Video Link'
        required: true

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
    - name: Install FFmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Start Streaming
      run: |
        ffmpeg -re -stream_loop -1 -i "${{ github.event.inputs.video_url }}" \
        -vf "scale=1280:720:force_original_aspect_ratio=decrease,pad=1280:720:(ow-iw)/2:(oh-ih)/2,format=yuv420p" \
        -vcodec libx264 -profile:v baseline -level 3.0 -maxrate 1500k -bufsize 3000k \
        -acodec aac -b:a 128k -ar 44100 \
        -f flv "rtmp://a.rtmp.youtube.com/live2/${{ secrets.YOUTUBE_STREAM_KEY }}"
