name: 24/7 Live Stream
on:
  workflow_dispatch:
    inputs:
      video_id:
        description: 'Google Drive File ID'
        required: true

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
    - name: Install FFmpeg and gdown
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg python3-pip
        sudo pip3 install --break-system-packages gdown

    - name: Download Video from Drive
      run: |
        gdown --id "${{ github.event.inputs.video_id }}" -O video.mp4

    - name: Start Streaming
      run: |
        ffmpeg -re -stream_loop -1 -i video.mp4 \
        -vcodec libx264 -pix_fmt yuv420p -maxrate 2048k -bufsize 2048k \
        -acodec aac -b:a 128k -ar 44100 \
        -f flv "rtmp://a.rtmp.youtube.com/live2/${{ secrets.YOUTUBE_STREAM_KEY }}"
